name: Branch Naming Convention Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          branch_name="${{ github.head_ref }}"
          if [[ ! "$branch_name" =~ ^(feature|hotfix|config)/[A-Z]+[-_]+[0-9]+[-_a-z]+$ ]]; then
            echo "Branch name '$branch_name' does not follow the naming convention!"
            exit 1
          fi
        shell: bash
