{
    "LABEL": {
      "name": "title needs formatting",
      "color": "EEEEEE"
    },
    "CHECKS": {
      "prefixes": ["[Bot] docs: "],
      "regexp": " ^(feature|hotfix|config)/[A-Z]+-[0-9]+-[a-zA-Z0-9\-]+$"
    },
    "MESSAGES": {
      "success": "PR title is valid",
      "failure": "PR title is invalid",
      "notice": "PR Title needs to pass regex '^(feat|fix|docs|test|ci|chore)!?(\\(.*\\))?!?:.*"
    }
  }
