name: Validate PR


on:
  pull_request:
    types: [opened, edited]
jobs:
  validate:
    runs-on: ubuntu-latest    
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: PR title
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        pr_body="${{ github.event.pull_request.body }}"
        if [[ ! "$pr_title" =~ ^(feature|hotfix|config)/$jira_ticket_pattern+-[a-zA-Z0-9_-]+$ ]]; then
          echo "wrong batch naming format"
          exit 1
        else
          echo "right naming"
        fi
